app:
  name: dsi-technical-test
  port: 8083

db:
  dialect: mysql
  host: localhost
  port: 3306
  db_name: dsi_technical # database name
  username: root # database user
  password: # database password

jwt:
  key: uwoww_sangad
  expired_minute: 30